### ISSUE TITLE
Undeclared dependency on `typing` module

### ISSUE THREAD

**Issue by DakotaNelson** [toidi/pyblockchain#1]
Pyblockchain seems to depend on `typing` without requiring it as a dependency in pip:

```
[dnelson@blueharvest blockchain-parsing]$ python
Python 3.4.2 (default, Jul 29 2015, 07:46:38) 
[GCC 4.9.2 20150212 (Red Hat 4.9.2-6)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from blockchain.reader import BlockchainFileReader
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/dnelson/.pyenv/versions/3.4.2/lib/python3.4/site-packages/blockchain/reader.py", line 4, in <module>
    from .block import Block
  File "/home/dnelson/.pyenv/versions/3.4.2/lib/python3.4/site-packages/blockchain/block.py", line 11, in <module>
    from typing import Sequence
ImportError: No module named 'typing'
>>> import typing
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named 'typing'
>>> 
[dnelson@blueharvest blockchain-parsing]$ pip install typing
Collecting typing
  Downloading typing-3.5.2.2.tar.gz (51kB)
    100% |████████████████████████████████| 51kB 2.1MB/s 
Installing collected packages: typing
  Running setup.py install for typing ... done
Successfully installed typing-3.5.2.2
[dnelson@blueharvest blockchain-parsing]$ python
Python 3.4.2 (default, Jul 29 2015, 07:46:38) 
[GCC 4.9.2 20150212 (Red Hat 4.9.2-6)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from blockchain.reader import BlockchainFileReader
>>> 
```

**Comment by ediskandarov-cur** [comment]
Currently `pyblockchain` works only with python 3.5 or newer.

**Comment by ediskandarov-cur** [comment]
@DakotaNelson I'll add https://pypi.python.org/pypi/backports.typing/1.1 to requirements.

**Comment by DakotaNelson** [comment]
Sounds great - thanks!

**Comment by ediskandarov-cur** [comment]
I added required packages but it's not enough. #2 

In my code - I used [`bytes.hex()`](http://python.readthedocs.io/en/latest/library/stdtypes.html#bytes.hex) method. Which is python 3.5 feature.

I'll try to fix that soon.

**Comment by ediskandarov-cur** [comment]
Sorry. I have no plans to support python older than 3.5

**Comment by DakotaNelson** [comment]
No worries, I wouldn't either. Thanks!
