### ISSUE TITLE
unpack_from requires a buffer of at least 88 bytes

### ISSUE THREAD

**Issue by DakotaNelson** [toidi/pyblockchain#3]
```
Current mmap position:  998179
Total mmap size:  134013860
Traceback (most recent call last):
  File "test.py", line 5, in <module>
    for block in block_reader:
  File "/home/dnelson/projects/blockchain-parsing/venv/lib/python3.5/site-packages/blockchain/reader.py", line 35, in __iter__
    raise err
  File "/home/dnelson/projects/blockchain-parsing/venv/lib/python3.5/site-packages/blockchain/reader.py", line 31, in __iter__
    block = Block.from_binary_data(blockchain_mview, offset=0)
  File "/home/dnelson/projects/blockchain-parsing/venv/lib/python3.5/site-packages/blockchain/block.py", line 412, in from_binary_data
    offset=offset,
  File "/home/dnelson/projects/blockchain-parsing/venv/lib/python3.5/site-packages/blockchain/block.py", line 130, in from_binary_data
    tup = struct.unpack_from(header_fmt, data, offset=offset)
struct.error: unpack_from requires a buffer of at least 88 bytes
```

This has happened on blocks 00600 and 00641 using the following code:

```
from blockchain.reader import BlockchainFileReader

block_reader = BlockchainFileReader('blocks/blk00600.dat')
for block in block_reader:
    pass
```

Any ideas as to what might be happening?

**Comment by ediskandarov-cur** [comment]
Do you mean that it happen on the first block in file `blocks/blk00600.dat`?

**Comment by DakotaNelson** [comment]
Ah, no - it parses through a fair number before it hits this error. I suspect that the last block in the file is a partial and so the code can't load the full block and crashes?

**Comment by dgrunberg** [comment]
This is because there is no check on reaching the end of the file.  I have a fix that I will make a pull request for.

**Comment by ediskandarov-cur** [comment]
@dgrunberg thank you!

**Comment by eventhorizonpl** [comment]
Hi,

I have similar problem.

```
        block_reader = BlockchainFileReader(self.dir_path + "\\" + file)

        for block in block_reader:
            self.analyse_block(block, file, time)
```

It happens on blk00975.dat from bitcoin blockchain.

```
Current mmap position:  999162
Total mmap size:  133632841
Traceback (most recent call last):
  File "manage.py", line 15, in <module>
    execute_from_command_line(sys.argv)
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Anaconda3_64\lib\site-packages\django\core\management\__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Anaconda3_64\lib\site-packages\django\core\management\__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Anaconda3_64\lib\site-packages\django\core\management\base.py", line 316, in run_from_argv
    self.execute(*args, **cmd_options)
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Anaconda3_64\lib\site-packages\django\core\management\base.py", line 353, in execute
    output = self.handle(*args, **options)
  File "Z:\crypto\crypto-bbs\stats\management\commands\bbs.py", line 113, in handle
    self.analyse()
  File "Z:\crypto\crypto-bbs\stats\management\commands\bbs.py", line 46, in analyse
    self.analyse_file(file)
  File "Z:\crypto\crypto-bbs\stats\management\commands\bbs.py", line 107, in analyse_file
    for block in block_reader:
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Anaconda3_64\lib\site-packages\blockchain\reader.py", line 35, in __iter__
    raise err
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Anaconda3_64\lib\site-packages\blockchain\reader.py", line 31, in __iter__
    block = Block.from_binary_data(blockchain_mview, offset=0)
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Anaconda3_64\lib\site-packages\blockchain\block.py", line 422, in from_binary_data
    offset=offset,
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Anaconda3_64\lib\site-packages\blockchain\block.py", line 342, in from_binary_data
    offset=offset,
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Anaconda3_64\lib\site-packages\blockchain\block.py", line 202, in from_binary_data
    offset=offset
struct.error: unpack_from requires a buffer of at least 4669693555745570203 bytes

```

4669693555745570203 bytes is a lot - I don't have so much on my laptop ;)

Any ideas how I can workaround this problem?

Best regards,
Michal

**Comment by eventhorizonpl** [comment]
@toidi ping

**Comment by ediskandarov-cur** [comment]
Hi @eventhorizonpl,
I haven't got a chance to look into that

@dgrunberg was going to push a PR with fix, but I didn't receive any.

Will try to find time to check the issue.

**Comment by eventhorizonpl** [comment]
@toidi 

I checked a commit history, and I've found this https://github.com/toidi/pyblockchain/commit/4b46fa69444cfde31d63ee5695ecaa46ff967646 so I was thinking, that PR was already merged.

Best regards,
Michal

**Comment by dgrunberg** [comment]
Yes, that PR was merged back in Dec 2017.  I think this problem is a different issue.

**Comment by Luigini** [comment]
Hi,
I'm newbie in Python Language and I need some help, please. My problem is similar to @eventhorizonpl and 

Executing test.py with blk00976.dat into block_reader, this error appears me in Block nº 33 into file blk00976.dat and program stops:
> Traceback (most recent call last):
  File "/home/donvito/Escritorio/pyblockchain/contrib/test.py", line 21, in <module>
    main()
  File "/home/donvito/Escritorio/pyblockchain/contrib/test.py", line 11, in main
    for i, block in enumerate(block_reader):
  File "/home/donvito/Escritorio/pyblockchain/blockchain/reader.py", line 35, in __iter__
    raise err
  File "/home/donvito/Escritorio/pyblockchain/blockchain/reader.py", line 31, in __iter__
    block = Block.from_binary_data(blockchain_mview, offset=0)  ##########################33
  File "/home/donvito/Escritorio/pyblockchain/blockchain/block.py", line 422, in from_binary_data
    offset=offset,
  File "/home/donvito/Escritorio/pyblockchain/blockchain/block.py", line 353, in from_binary_data
    offset=offset,
  File "/home/donvito/Escritorio/pyblockchain/blockchain/block.py", line 273, in from_binary_data
    public_key, = struct.unpack_from(public_key_fmt, data, offset=offset)
struct.error: unpack_from requires a buffer of at least 2164260863 bytes
`

Executing from blk00979 to blk00999 , the error is: 
`OverflowError: Python int too large to convert to C long`

And from blk01000.dat to final blkXXXXX.dat which I've downloaded it (blk01565.dat in this case), the errors are the same as mentioned above or simply: `MemoryError`

I'm stuck and I do not know how to continue, because the files .dat before blk00976.dat works fine... I wish you can help me fix the problem soon

Regards!

**Comment by DakotaNelson** [comment]
Have you tried this on different files? The original problem I had was because the `blk` files I was using were corrupted, so re-downloading the files solved it - the problem was corrupt data, not pyblockchain.

**Comment by Luigini** [comment]
> Have you tried this on different files? The original problem I had was because the `blk` files I was using were corrupted, so re-downloading the files solved it - the problem was corrupt data, not pyblockchain.

Yeah @DakotaNelson. 
I  re-downloaded these files and I don't solved it. I read in forums and i found this:

[https://bitcointalk.org/index.php?topic=4459540.0](url)

I think the error can be for new Extended transaction types which were added some years ago

/ **
  * Basic transaction serialization format:
  * - int32_t nVersion
  * - std :: vector <CTxIn> vin
  * - std :: vector <CTxOut> vout
  * - uint32_t nLockTime
  *
  * Extended transaction serialization format:
  * - int32_t nVersion
  * - unsigned char dummy = 0x00
  * - unsigned char flags (! = 0)
  * - std :: vector <CTxIn> vin
  * - std :: vector <CTxOut> vout
  * - if (flags & 1):
  * - CTxWitness wit;
  * - uint32_t nLockTime
  * /

I don't know if I'm right...

**Comment by ediskandarov-cur** [comment]
@Luigini , thanks for the hint
worth checking

I'll look into that this weekend

**Comment by Luigini** [comment]
@toidi Thank you very much.

I am trying to read until 15XX.dat but my Python notions are minimal, I can't  program something convincing to parse the rest of the files...I'm still stuck in block 00976.dat...

**Comment by eventhorizonpl** [comment]
@toidi 

Hi,

Have you managed to look at this problem?

Best regards,
Michal
